### PR TITLE
add glitch embed for projects

### PR DESCRIPTION
**Pull request by khalby786**
Add Glitch embeds on project pages for each projects.

image

https://deploy-preview-1--awesomeprojects.netlify.app/

### CODE REVIEW

**Review by aboutDavid — CHANGES_REQUESTED** [review]
In line 36, can you change `oroject.title` to `project.title` please?

**Comment by khalby786** [comment]
😅  didn't notice that

**Comment by khalby786** [comment]
Ok, fixed that.

**Comment by aboutDavid** [comment]
Thank you!

**Pull request merged**
